function PartialProjectList()
{
  return [
'<div class="container-fluid">\n',
'  <div class="row">\n',
'    <div class="col-md-2">\n',
'      <!--Sidebar content-->\n',
'      <h1>My Bio</h1>\n',
'      <div class="bio">\n',
'        <img class="photo" ng-src="{{user.photoUrl}}"/>\n',
'        <div class="name">{{user.name}}</div>\n',
'        <ul class="degrees">\n',
'          <li ng-repeat="degree in user.degree"\n',
'              class="degree">\n',
'              <img class="country-icon" ng-src="{{degree.icon}}"/>\n',
'              {{degree.title}}\n',
'          </li>\n',
'        </ul>\n',
'        <br/>\n',
'        <div class="cv">\n',
'          <a target="_blank" ng-href="{{user.cv}}">\n',
'            <img class="ref-icon" ng-src="img/core/pdf.png"/>\n',
'          </a>\n',
'          <a target="_blank" ng-href="{{user.cv}}">\n',
'            CV (R&eacute;sum&eacute;)\n',
'          </a>\n',
'        </div>        \n',
'        <div class="linkedIn">\n',
'          <a target="_blank" target="_blank" ng-href="{{user.labUrl}}">\n',
'            <img class="ref-icon" ng-src="img/core/linkedin.png"/>\n',
'          </a>\n',
'          <a target="_blank" target="_blank" ng-href="{{user.linkedInUrl}}">LinkedIn Profile</a>\n',
'        </div>\n',
'        <div class="labUrl">\n',
'          <a target="_blank" ng-href="{{user.labUrl}}">\n',
'            <img class="ref-icon" ng-src="img/core/gsdlab.png"/>\n',
'          </a>\n',
'          <a target="_blank" ng-href="{{user.labUrl}}">\n',
'            Laboratory Homepage\n',
'          </a>\n',
'        </div>        \n',
'        <br/>\n',
'        <div class="status-title">Current status:</div> \n',
'        <div class="status">{{user.status}}</div>      \n',
'      </div>\n',
'      <h1>Contact Me</h1>\n',
'      <div class="contact">\n',
'        <div class="email">\n',
'          <a target="_blank" href="mailto:{{user.email}}">\n',
'            <img class="ref-icon" ng-src="img/core/email.png"/>\n',
'          </a>          \n',
'          <a target="_blank" class="email" href="mailto:{{user.email}}">{{user.email}}</a>\n',
'        </div>\n',
'        <div class="call">\n',
'          <img class="ref-icon" ng-src="img/core/call.png"/>\n',
'          <span class="call">{{user.phone}}</span>\n',
'        </div>\n',
'      </div>\n',
'    </div>\n',
'    <div class="col-md-10">\n',
'      <!--Body content-->\n',
'      <h1>My Top Projects</h1>\n',
'      Search: <input ng-model="query">\n',
'      Sort by:\n',
'      <select ng-model="orderProp">\n',
'        <option value="name">Alphabet</option>\n',
'        <option value="weight">Coolness</option>\n',
'      </select>\n',
'      <br/>\n',
'      <br/>\n',
'      <ul class="projects">\n',
'        <li ng-repeat="project in projects | filter:query | orderBy:orderProp"\n',
'            class="thumbnail project-listing">\n',
'          <a href="index.html#show/project/{{project.id}}" class="thumb"><img ng-src="{{project.imageUrl}}"></a>\n',
'          <a href="index.html#show/project/{{project.id}}">{{project.name}}</a>\n',
'          <p>{{project.snippet}}</p>\n',
'        </li>\n',
'      </ul>\n',
'\n',
'    </div>\n',
'  </div>\n',
'</div>'
].join("");
}